name: CI
on: push
jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Install dependencies
        run: yarn

      - name: Deploy
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          git remote set-url origin https://x-access-token:${{ github.virtualBackground }}@github.com/VedantKhairnar/virtual-background-msa.git
          yarn deploy -u "GitHub Actions <github-actions@users.noreply.github.com>"
